LANG = {
    "uz": {
        "welcome": "Salom! PulKeeper 🛡️\n\nXarajat kiriting:\nMisol: <code>obid 25000</code>",
        "added": "Xarajat yozildi",
        "bad_amount": "Summani topib bo‘lmadi.\nMisol: <code>taksi 18000</code>",
        "no_data": "Hali statistik ma’lumot yo‘q 🤷‍♂️",
        "stat_title": "📊 Xarajatlar statistikasi",
        "today": "Bugun",
        "week": "7 kun",
        "month": "Oy",
        "choose_lang": "🇺🇿 Tilni tanlang / 🇷🇺 Выберите язык",
        "uzbek": "🇺🇿 O‘zbekcha",
        "russian": "🇷🇺 Русский",
        "balance_title": "Balans",
        "history_title": "🧾 So'nggi xarajatlar",
        "history_empty": "Hozircha xarajatlar tarixi yo'q.",
    },
    "ru": {
        "welcome": "Привет! PulKeeper 🛡️\n\nВведите расход:\nНапример: <code>такси 18000</code>",
        "added": "Расход записан",
        "bad_amount": "Не удалось определить сумму.\nПример: <code>обед 25000</code>",
        "no_data": "Статистики пока нет 🤷‍♂️",
        "stat_title": "📊 Статистика расходов",
        "today": "Сегодня",
        "week": "7 дней",
        "month": "Месяц",
        "choose_lang": "🇺🇿 Tilni tanlang / 🇷🇺 Выберите язык",
        "uzbek": "🇺🇿 O‘zbekcha",
        "russian": "🇷🇺 Русский",
        "balance_title": "Баланс",
        "history_title": "🧾 Последние расходы",
        "history_empty": "История расходов пока пуста.",
    },
    "en": {
        "welcome": "Welcome to PulKeeper 🛡️\n\nEnter expense:\nExample: <code>food 25000</code>",
        "added": "Expense recorded",
        "bad_amount": "Couldn't detect amount.\nExample: <code>food 25000</code>",
        "no_data": "No stats yet 🤷‍♂️",
        "stat_title": "📊 Expense statistics",
        "today": "Today",
        "week": "7 days",
        "month": "Month",
        "balance_title": "Balance",
        "history_title": "🧾 Recent expenses",
        "history_empty": "No expense history yet.",
    }
}
